package entidade;
// Generated 21/09/2013 16:52:20 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="contromidia"
)
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nomeUsuario;
     private String email;
     private String senha;
     private String perfil;
     private Set usuarios = new HashSet(0);

    public Cliente() {
    	
    	this.idCliente = 0;
    	this.nomeUsuario = "";
        this.email = "";
        this.senha = "";
        this.perfil = "";
        
    	
    }

	
    public Cliente(String nomeUsuario, String email, String senha, String perfil) {
        this.nomeUsuario = nomeUsuario;
        this.email = email;
        this.senha = senha;
        this.perfil = perfil;
    }
    public Cliente(String nomeUsuario, String email, String senha, String perfil, Set usuarios) {
       this.nomeUsuario = nomeUsuario;
       this.email = email;
       this.senha = senha;
       this.perfil = perfil;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCliente", unique=true, nullable=false)
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    
    @Column(name="nomeUsuario", unique=true, nullable=false, length=50)
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }
    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="senha", nullable=false, length=60)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    @Column(name="perfil", nullable=false, length=10)
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


