package entidade;
// Generated 21/09/2013 16:52:20 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name="materia"
    ,catalog="contromidia"
)
public class Materia  implements java.io.Serializable {


     private Integer idMateria;
     private String padrao;
     private String veiculo;
     private String assunto;
     private String nomeDoArquivo;
     private String extensao;
     private Date data;
     private String indice;
     private String apresentador;
     private String critica;
     private String emissora;
     private String hora;
     private String nomePrograma;
     private Set usuarioHasMaterias = new HashSet(0);

    public Materia() {
    	
    	this.veiculo = "";
        this.assunto = "";
        this.extensao = "assunto";
        this.apresentador = "";
        this.nomePrograma = "";
    	
    }

	
    public Materia(String padrao, String veiculo, String assunto, String nomeDoArquivo, String extensao, Date data) {
        this.padrao = padrao;
        this.veiculo = veiculo;
        this.assunto = assunto;
        this.nomeDoArquivo = nomeDoArquivo;
        this.extensao = extensao;
        this.data = data;
    }
    public Materia(String padrao, String veiculo, String assunto, String nomeDoArquivo, String extensao, Date data, String indice, String apresentador, String critica, String emissora, String hora, String nomePrograma, Set usuarioHasMaterias) {
       this.padrao = padrao;
       this.veiculo = veiculo;
       this.assunto = assunto;
       this.nomeDoArquivo = nomeDoArquivo;
       this.extensao = extensao;
       this.data = data;
       this.indice = indice;
       this.apresentador = apresentador;
       this.critica = critica;
       this.emissora = emissora;
       this.hora = hora;
       this.nomePrograma = nomePrograma;
       this.usuarioHasMaterias = usuarioHasMaterias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idMateria", unique=true, nullable=false)
    public Integer getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
    }
    
    @Column(name="padrao", nullable=false, length=250)
    public String getPadrao() {
        return this.padrao;
    }
    
    public void setPadrao(String padrao) {
        this.padrao = padrao;
    }
    
    @Column(name="veiculo", nullable=false, length=20)
    public String getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(String veiculo) {
        this.veiculo = veiculo;
    }
    
    @Column(name="assunto", nullable=false)
    public String getAssunto() {
        return this.assunto;
    }
    
    public void setAssunto(String assunto) {
        this.assunto = assunto;
    }
    
    @Column(name="nomeDoArquivo", nullable=false, length=200)
    public String getNomeDoArquivo() {
        return this.nomeDoArquivo;
    }
    
    public void setNomeDoArquivo(String nomeDoArquivo) {
        this.nomeDoArquivo = nomeDoArquivo;
    }
    
    @Column(name="extensao", nullable=false, length=120)
    public String getExtensao() {
        return this.extensao;
    }
    
    public void setExtensao(String extensao) {
        this.extensao = extensao;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="data", nullable=false, length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    
    @Column(name="indice", length=65535)
    public String getIndice() {
        return this.indice;
    }
    
    public void setIndice(String indice) {
        this.indice = indice;
    }
    
    @Column(name="apresentador", length=50)
    public String getApresentador() {
        return this.apresentador;
    }
    
    public void setApresentador(String apresentador) {
        this.apresentador = apresentador;
    }
    
    @Column(name="critica", length=10)
    public String getCritica() {
        return this.critica;
    }
    
    public void setCritica(String critica) {
        this.critica = critica;
    }
    
    @Column(name="emissora", length=30)
    public String getEmissora() {
        return this.emissora;
    }
    
    public void setEmissora(String emissora) {
        this.emissora = emissora;
    }
    
    @Column(name="hora", length=8)
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    
    @Column(name="nomePrograma", length=45)
    public String getNomePrograma() {
        return this.nomePrograma;
    }
    
    public void setNomePrograma(String nomePrograma) {
        this.nomePrograma = nomePrograma;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="materia")
    public Set getUsuarioHasMaterias() {
        return this.usuarioHasMaterias;
    }
    
    public void setUsuarioHasMaterias(Set usuarioHasMaterias) {
        this.usuarioHasMaterias = usuarioHasMaterias;
    }




}


