package entidade;
// Generated 20/09/2013 20:58:17 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioId generated by hbm2java
 */
@Embeddable
public class UsuarioId  implements java.io.Serializable {


     private int idUsuario;
     private int clienteIdCliente;

    public UsuarioId() {
    }

    public UsuarioId(int idUsuario, int clienteIdCliente) {
       this.idUsuario = idUsuario;
       this.clienteIdCliente = clienteIdCliente;
    }
   

    @Column(name="idUsuario", nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Column(name="Cliente_idCliente", nullable=false)
    public int getClienteIdCliente() {
        return this.clienteIdCliente;
    }
    
    public void setClienteIdCliente(int clienteIdCliente) {
        this.clienteIdCliente = clienteIdCliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioId) ) return false;
		 UsuarioId castOther = ( UsuarioId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && (this.getClienteIdCliente()==castOther.getClienteIdCliente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + this.getClienteIdCliente();
         return result;
   }   


}


