package entidade;
// Generated 21/09/2013 16:52:20 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuarioHasMateria generated by hbm2java
 */
@Entity
@Table(name="usuario_has_materia"
    ,catalog="contromidia"
)
public class UsuarioHasMateria  implements java.io.Serializable {


     private UsuarioHasMateriaId id;
     private Usuario usuario;
     private Materia materia;
     private String estatus;
     private String solicitacao;
     private Date data;

    public UsuarioHasMateria() {
    }

	
    public UsuarioHasMateria(UsuarioHasMateriaId id, Usuario usuario, Materia materia, String estatus, Date data) {
        this.id = id;
        this.usuario = usuario;
        this.materia = materia;
        this.estatus = estatus;
        this.data = data;
    }
    public UsuarioHasMateria(UsuarioHasMateriaId id, Usuario usuario, Materia materia, String estatus, String solicitacao, Date data) {
       this.id = id;
       this.usuario = usuario;
       this.materia = materia;
       this.estatus = estatus;
       this.solicitacao = solicitacao;
       this.data = data;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="usuarioIdUsuario", column=@Column(name="Usuario_idUsuario", nullable=false) ), 
        @AttributeOverride(name="materiaIdMateria", column=@Column(name="Materia_idMateria", nullable=false) ) } )
    public UsuarioHasMateriaId getId() {
        return this.id;
    }
    
    public void setId(UsuarioHasMateriaId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Usuario_idUsuario", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Materia_idMateria", nullable=false, insertable=false, updatable=false)
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    
    @Column(name="estatus", nullable=false, length=15)
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    
    @Column(name="solicitacao", nullable=true, length=1)
    public String getSolicitacao() {
        return this.solicitacao;
    }
    
    public void setSolicitacao(String solicitacao) {
        this.solicitacao = solicitacao;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="data", nullable=false, length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


