package entidade;
// Generated 21/09/2013 16:52:20 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import login.Perfil;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="contromidia"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Cliente cliente;
     private String nomeUsuario;
     private String email;
     private String senha;
     private String perfil;
     private Set usuarioHasMaterias = new HashSet(0);

    public Usuario() {
    	
    	cliente = new Cliente();
    	
    }

	
    public Usuario(Cliente cliente, String nomeUsuario, String email, String senha, String perfil) {
        this.cliente = cliente;
        this.nomeUsuario = nomeUsuario;
        this.email = email;
        this.senha = senha;
        this.perfil = perfil;
    }
    public Usuario(Cliente cliente, String nomeUsuario, String email, String senha, String perfil, Set usuarioHasMaterias) {
       this.cliente = cliente;
       this.nomeUsuario = nomeUsuario;
       this.email = email;
       this.senha = senha;
       this.perfil = perfil;
       this.usuarioHasMaterias = usuarioHasMaterias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idUsuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cliente_idCliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    @Column(name="nomeUsuario", unique=true, nullable=false, length=50)
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }
    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="senha", nullable=false, length=60)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    @Column(name="perfil", nullable=false, length=10)
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="usuario")
    public Set getUsuarioHasMaterias() {
        return this.usuarioHasMaterias;
    }
    
    public void setUsuarioHasMaterias(Set usuarioHasMaterias) {
        this.usuarioHasMaterias = usuarioHasMaterias;
    }


    public boolean temAcesso(String pagina, String perf) {


    	Perfil p = new Perfil(perf);



    	return p.temAcesso(pagina);
    }

}


